<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6c57c1a9-10a7-430c-9db5-685eb25e99e5</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/form[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.wyhvVD</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'wyhvVD _1EApiB hq6WM5 L-VL8Q cepDQ1 _7w24N1')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>wyhvVD _1EApiB hq6WM5 L-VL8Q cepDQ1 _7w24N1</value>
        <webElementGuid>cd6bd013-a74e-487e-8b40-7a1a97d5afd1</webElementGuid>
    </webElementProperties>
</WebElementEntity>